<script>
	import { Chart, Card, A, Button, Dropdown, DropdownItem, Popover } from 'flowbite-svelte';
	import { Section, Maintenance } from 'flowbite-svelte-blocks';
	import {
		InfoCircleSolid,
		ChevronDownSolid,
		ChevronRightSolid,
		PenSolid,
		DownloadSolid,
		ShareNodesSolid,
		TrashBinSolid,
		DotsHorizontalOutline,
		ArrowUpSolid
	} from 'flowbite-svelte-icons';

	let underDevelopment = true;

	const chart_types = ['area', 'line', 'bar', 'radialBar', 'pie', 'donut'];
	const options = {
		series: [52.8, 26.8, 20.4],
		colors: ['#1C64F2', '#16BDCA', '#9061F9'],
		chart: {
			height: 420,
			width: '100%',
			type: 'pie'
		},
		stroke: {
			colors: ['white'],
			lineCap: ''
		},
		plotOptions: {
			pie: {
				labels: {
					show: true
				},
				size: '100%',
				dataLabels: {
					offset: -25
				}
			}
		},
		labels: ['Direct', 'Organic search', 'Referrals'],
		dataLabels: {
			enabled: true,
			style: {
				fontFamily: 'Inter, sans-serif'
			}
		},
		legend: {
			position: 'bottom',
			fontFamily: 'Inter, sans-serif'
		},
		yaxis: {
			labels: {
				formatter: function (value) {
					return value + '%';
				}
			}
		},
		xaxis: {
			labels: {
				formatter: function (value) {
					return value + '%';
				}
			},
			axisTicks: {
				show: false
			},
			axisBorder: {
				show: false
			}
		}
	};

	const options2 = {
		series: [
			{
				name: 'Income',
				color: '#31C48D',
				data: ['1420', '1620', '1820', '1420', '1650', '2120']
			},
			{
				name: 'Expense',
				data: ['788', '810', '866', '788', '1100', '1200'],
				color: '#F05252'
			}
		],
		chart: {
			sparkline: {
				enabled: false
			},
			type: 'bar',
			width: '100%',
			height: 400,
			toolbar: {
				show: false
			}
		},
		fill: {
			opacity: 1
		},
		plotOptions: {
			bar: {
				horizontal: true,
				columnWidth: '100%',
				borderRadiusApplication: 'end',
				borderRadius: 6,
				dataLabels: {
					position: 'top'
				}
			}
		},
		legend: {
			show: true,
			position: 'bottom'
		},
		dataLabels: {
			enabled: false
		},
		tooltip: {
			shared: true,
			intersect: false,
			formatter: function (value) {
				return '$' + value;
			}
		},
		xaxis: {
			labels: {
				show: true,
				style: {
					fontFamily: 'Inter, sans-serif',
					cssClass: 'text-xs font-normal fill-gray-500 dark:fill-gray-400'
				},
				formatter: function (value) {
					return '$' + value;
				}
			},
			categories: ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
			axisTicks: {
				show: false
			},
			axisBorder: {
				show: false
			}
		},
		yaxis: {
			labels: {
				show: true,
				style: {
					fontFamily: 'Inter, sans-serif',
					cssClass: 'text-xs font-normal fill-gray-500 dark:fill-gray-400'
				}
			}
		},
		grid: {
			show: true,
			strokeDashArray: 4,
			padding: {
				left: 2,
				right: 2,
				top: -20
			}
		}
	};
</script>

{#if underDevelopment}
	<Section name="maintenance">
		<Maintenance>
			<svelte:fragment slot="h1">Under Maintenance</svelte:fragment>
			<svelte:fragment slot="paragraph"
				>Our Enterprise administrators are performing scheduled maintenance.</svelte:fragment
			>
		</Maintenance>
	</Section>
{:else}
	<Card padding="md" size="xl" class="grid md:grid-cols-2">
		<div class="flex justify-between items-start w-full">
			<div class="flex-col items-center">
				<div class="flex items-center mb-1">
					<h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white me-1">
						Website traffic
					</h5>
					<InfoCircleSolid
						id="pie1"
						class="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1"
					/>
					<Popover
						triggeredBy="#pie1"
						class="text-sm text-gray-500 bg-white border border-gray-200 rounded-lg shadow-sm w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400 z-10"
					>
						<div class="p-3 space-y-2">
							<h3 class="font-semibold text-gray-900 dark:text-white">
								Activity growth - Incremental
							</h3>
							<p>
								Report helps navigate cumulative growth of community activities. Ideally, the chart
								should have a growing trend, as stagnating chart signifies a significant decrease of
								community activity.
							</p>
							<h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
							<p>
								For each date bucket, the all-time volume of activities is calculated. This means
								that activities in period n contain all activities up to period n, plus the
								activities generated by your community in period.
							</p>
							<A href="/">Read more <ChevronRightSolid class="w-2 h-2 ms-1.5" /></A>
						</div>
					</Popover>
				</div>
			</div>
			<div class="flex justify-end items-center">
				<DotsHorizontalOutline id="dots-menu" class="dots-menu dark:text-white" />
				<Dropdown triggeredBy="#dots-menu" class="w-44" offset="-6">
					<DropdownItem><PenSolid class="inline w-3 h-3 me-2" /> Edit widget</DropdownItem>
					<DropdownItem><DownloadSolid class="inline w-3 h-3 me-2" />Dropdown data</DropdownItem>
					<DropdownItem
						><ShareNodesSolid class="inline w-3 h-3 me-2" />Add to repository</DropdownItem
					>
					<DropdownItem><TrashBinSolid class="inline w-3 h-3 me-2" />Delete widget</DropdownItem>
				</Dropdown>
			</div>
		</div>

		<Chart {options} class="py-6" />

		<div
			class="grid grid-cols-1 items-center border-gray-200 border-t dark:border-gray-700 justify-between"
		>
			<div class="flex justify-between items-center pt-5">
				<Button
					class="text-sm font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 text-center inline-flex items-center dark:hover:text-white bg-transparent hover:bg-transparent dark:bg-transparent dark:hover:bg-transparent focus:ring-transparent dark:focus:ring-transparent py-0"
					>Last 7 days<ChevronDownSolid class="w-2.5 m-2.5 ms-1.5" /></Button
				>
				<Dropdown class="w-40" offset="-6">
					<DropdownItem>Yesterday</DropdownItem>
					<DropdownItem>Today</DropdownItem>
					<DropdownItem>Last 7 days</DropdownItem>
					<DropdownItem>Last 30 days</DropdownItem>
					<DropdownItem>Last 90 days</DropdownItem>
				</Dropdown>
				<A
					href="/"
					class="uppercase text-sm font-semibold hover:text-primary-700 dark:hover:text-primary-500 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700 px-3 py-2 hover:no-underline"
				>
					Traffic analysis
					<ChevronRightSolid class="w-2.5 h-2.5 ms-1.5" />
				</A>
			</div>
		</div>
	</Card>
{/if}
