/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BlockPrice
 */
export interface BlockPrice {
	/**
	 *
	 * @type {string}
	 * @memberof BlockPrice
	 */
	unitName?: string;
	/**
	 *
	 * @type {number}
	 * @memberof BlockPrice
	 */
	size?: number;
	/**
	 *
	 * @type {number}
	 * @memberof BlockPrice
	 */
	price?: number;
	/**
	 *
	 * @type {number}
	 * @memberof BlockPrice
	 */
	max?: number;
}

/**
 * Check if a given object implements the BlockPrice interface.
 */
export function instanceOfBlockPrice(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function BlockPriceFromJSON(json: any): BlockPrice {
	return BlockPriceFromJSONTyped(json, false);
}

export function BlockPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockPrice {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		unitName: !exists(json, 'unitName') ? undefined : json['unitName'],
		size: !exists(json, 'size') ? undefined : json['size'],
		price: !exists(json, 'price') ? undefined : json['price'],
		max: !exists(json, 'max') ? undefined : json['max']
	};
}

export function BlockPriceToJSON(value?: BlockPrice | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		unitName: value.unitName,
		size: value.size,
		price: value.price,
		max: value.max
	};
}
