/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogValidationError } from './CatalogValidationError';
import {
	CatalogValidationErrorFromJSON,
	CatalogValidationErrorFromJSONTyped,
	CatalogValidationErrorToJSON
} from './CatalogValidationError';

/**
 *
 * @export
 * @interface CatalogValidation
 */
export interface CatalogValidation {
	/**
	 *
	 * @type {Array<CatalogValidationError>}
	 * @memberof CatalogValidation
	 */
	catalogValidationErrors?: Array<CatalogValidationError>;
}

/**
 * Check if a given object implements the CatalogValidation interface.
 */
export function instanceOfCatalogValidation(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function CatalogValidationFromJSON(json: any): CatalogValidation {
	return CatalogValidationFromJSONTyped(json, false);
}

export function CatalogValidationFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): CatalogValidation {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		catalogValidationErrors: !exists(json, 'catalogValidationErrors')
			? undefined
			: (json['catalogValidationErrors'] as Array<any>).map(CatalogValidationErrorFromJSON)
	};
}

export function CatalogValidationToJSON(value?: CatalogValidation | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		catalogValidationErrors:
			value.catalogValidationErrors === undefined
				? undefined
				: (value.catalogValidationErrors as Array<any>).map(CatalogValidationErrorToJSON)
	};
}
