/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PluginProperty } from './PluginProperty';
import {
	PluginPropertyFromJSON,
	PluginPropertyFromJSONTyped,
	PluginPropertyToJSON
} from './PluginProperty';

/**
 *
 * @export
 * @interface HostedPaymentPageFields
 */
export interface HostedPaymentPageFields {
	/**
	 *
	 * @type {Array<PluginProperty>}
	 * @memberof HostedPaymentPageFields
	 */
	formFields?: Array<PluginProperty>;
}

/**
 * Check if a given object implements the HostedPaymentPageFields interface.
 */
export function instanceOfHostedPaymentPageFields(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function HostedPaymentPageFieldsFromJSON(json: any): HostedPaymentPageFields {
	return HostedPaymentPageFieldsFromJSONTyped(json, false);
}

export function HostedPaymentPageFieldsFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): HostedPaymentPageFields {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		formFields: !exists(json, 'formFields')
			? undefined
			: (json['formFields'] as Array<any>).map(PluginPropertyFromJSON)
	};
}

export function HostedPaymentPageFieldsToJSON(value?: HostedPaymentPageFields | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		formFields:
			value.formFields === undefined
				? undefined
				: (value.formFields as Array<any>).map(PluginPropertyToJSON)
	};
}
