/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuditLog } from './AuditLog';
import { AuditLogFromJSON, AuditLogFromJSONTyped, AuditLogToJSON } from './AuditLog';

/**
 *
 * @export
 * @interface HostedPaymentPageFormDescriptor
 */
export interface HostedPaymentPageFormDescriptor {
	/**
	 *
	 * @type {string}
	 * @memberof HostedPaymentPageFormDescriptor
	 */
	kbAccountId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof HostedPaymentPageFormDescriptor
	 */
	formMethod?: string;
	/**
	 *
	 * @type {string}
	 * @memberof HostedPaymentPageFormDescriptor
	 */
	formUrl?: string;
	/**
	 *
	 * @type {{ [key: string]: object; }}
	 * @memberof HostedPaymentPageFormDescriptor
	 */
	formFields?: { [key: string]: object };
	/**
	 *
	 * @type {{ [key: string]: object; }}
	 * @memberof HostedPaymentPageFormDescriptor
	 */
	properties?: { [key: string]: object };
	/**
	 *
	 * @type {Array<AuditLog>}
	 * @memberof HostedPaymentPageFormDescriptor
	 */
	auditLogs?: Array<AuditLog>;
}

/**
 * Check if a given object implements the HostedPaymentPageFormDescriptor interface.
 */
export function instanceOfHostedPaymentPageFormDescriptor(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function HostedPaymentPageFormDescriptorFromJSON(
	json: any
): HostedPaymentPageFormDescriptor {
	return HostedPaymentPageFormDescriptorFromJSONTyped(json, false);
}

export function HostedPaymentPageFormDescriptorFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): HostedPaymentPageFormDescriptor {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		kbAccountId: !exists(json, 'kbAccountId') ? undefined : json['kbAccountId'],
		formMethod: !exists(json, 'formMethod') ? undefined : json['formMethod'],
		formUrl: !exists(json, 'formUrl') ? undefined : json['formUrl'],
		formFields: !exists(json, 'formFields') ? undefined : json['formFields'],
		properties: !exists(json, 'properties') ? undefined : json['properties'],
		auditLogs: !exists(json, 'auditLogs')
			? undefined
			: (json['auditLogs'] as Array<any>).map(AuditLogFromJSON)
	};
}

export function HostedPaymentPageFormDescriptorToJSON(
	value?: HostedPaymentPageFormDescriptor | null
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		kbAccountId: value.kbAccountId,
		formMethod: value.formMethod,
		formUrl: value.formUrl,
		formFields: value.formFields,
		properties: value.properties,
		auditLogs:
			value.auditLogs === undefined
				? undefined
				: (value.auditLogs as Array<any>).map(AuditLogToJSON)
	};
}
