/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OverdueStateConfig } from './OverdueStateConfig';
import {
    OverdueStateConfigFromJSON,
    OverdueStateConfigFromJSONTyped,
    OverdueStateConfigToJSON,
} from './OverdueStateConfig';

/**
 * 
 * @export
 * @interface Overdue
 */
export interface Overdue {
    /**
     * 
     * @type {number}
     * @memberof Overdue
     */
    initialReevaluationInterval?: number;
    /**
     * 
     * @type {Array<OverdueStateConfig>}
     * @memberof Overdue
     */
    overdueStates?: Array<OverdueStateConfig>;
}

/**
 * Check if a given object implements the Overdue interface.
 */
export function instanceOfOverdue(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OverdueFromJSON(json: any): Overdue {
    return OverdueFromJSONTyped(json, false);
}

export function OverdueFromJSONTyped(json: any, ignoreDiscriminator: boolean): Overdue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'initialReevaluationInterval': !exists(json, 'initialReevaluationInterval') ? undefined : json['initialReevaluationInterval'],
        'overdueStates': !exists(json, 'overdueStates') ? undefined : ((json['overdueStates'] as Array<any>).map(OverdueStateConfigFromJSON)),
    };
}

export function OverdueToJSON(value?: Overdue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'initialReevaluationInterval': value.initialReevaluationInterval,
        'overdueStates': value.overdueStates === undefined ? undefined : ((value.overdueStates as Array<any>).map(OverdueStateConfigToJSON)),
    };
}

