/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OverdueState
 */
export interface OverdueState {
    /**
     * 
     * @type {string}
     * @memberof OverdueState
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OverdueState
     */
    externalMessage?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OverdueState
     */
    isDisableEntitlementAndChangesBlocked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OverdueState
     */
    isBlockChanges?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OverdueState
     */
    isClearState?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OverdueState
     */
    reevaluationIntervalDays?: number;
}

/**
 * Check if a given object implements the OverdueState interface.
 */
export function instanceOfOverdueState(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OverdueStateFromJSON(json: any): OverdueState {
    return OverdueStateFromJSONTyped(json, false);
}

export function OverdueStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverdueState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'externalMessage': !exists(json, 'externalMessage') ? undefined : json['externalMessage'],
        'isDisableEntitlementAndChangesBlocked': !exists(json, 'isDisableEntitlementAndChangesBlocked') ? undefined : json['isDisableEntitlementAndChangesBlocked'],
        'isBlockChanges': !exists(json, 'isBlockChanges') ? undefined : json['isBlockChanges'],
        'isClearState': !exists(json, 'isClearState') ? undefined : json['isClearState'],
        'reevaluationIntervalDays': !exists(json, 'reevaluationIntervalDays') ? undefined : json['reevaluationIntervalDays'],
    };
}

export function OverdueStateToJSON(value?: OverdueState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'externalMessage': value.externalMessage,
        'isDisableEntitlementAndChangesBlocked': value.isDisableEntitlementAndChangesBlocked,
        'isBlockChanges': value.isBlockChanges,
        'isClearState': value.isClearState,
        'reevaluationIntervalDays': value.reevaluationIntervalDays,
    };
}

