/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuditLog } from './AuditLog';
import {
    AuditLogFromJSON,
    AuditLogFromJSONTyped,
    AuditLogToJSON,
} from './AuditLog';
import type { PluginProperty } from './PluginProperty';
import {
    PluginPropertyFromJSON,
    PluginPropertyFromJSONTyped,
    PluginPropertyToJSON,
} from './PluginProperty';

/**
 * 
 * @export
 * @interface PaymentAttempt
 */
export interface PaymentAttempt {
    /**
     * 
     * @type {string}
     * @memberof PaymentAttempt
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttempt
     */
    paymentMethodId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttempt
     */
    paymentExternalKey?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttempt
     */
    transactionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttempt
     */
    transactionExternalKey?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttempt
     */
    transactionType?: PaymentAttemptTransactionTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof PaymentAttempt
     */
    effectiveDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttempt
     */
    stateName?: string;
    /**
     * Transaction amount, required except for void operations
     * @type {number}
     * @memberof PaymentAttempt
     */
    amount?: number;
    /**
     * Amount currency (account currency unless specified)
     * @type {string}
     * @memberof PaymentAttempt
     */
    currency?: PaymentAttemptCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttempt
     */
    pluginName?: string;
    /**
     * 
     * @type {Array<PluginProperty>}
     * @memberof PaymentAttempt
     */
    pluginProperties?: Array<PluginProperty>;
    /**
     * 
     * @type {Array<AuditLog>}
     * @memberof PaymentAttempt
     */
    auditLogs?: Array<AuditLog>;
}


/**
 * @export
 */
export const PaymentAttemptTransactionTypeEnum = {
    Authorize: 'AUTHORIZE',
    Capture: 'CAPTURE',
    Chargeback: 'CHARGEBACK',
    Credit: 'CREDIT',
    Purchase: 'PURCHASE',
    Refund: 'REFUND',
    Void: 'VOID'
} as const;
export type PaymentAttemptTransactionTypeEnum = typeof PaymentAttemptTransactionTypeEnum[keyof typeof PaymentAttemptTransactionTypeEnum];

/**
 * @export
 */
export const PaymentAttemptCurrencyEnum = {
    Aed: 'AED',
    Afn: 'AFN',
    All: 'ALL',
    Amd: 'AMD',
    Ang: 'ANG',
    Aoa: 'AOA',
    Ars: 'ARS',
    Aud: 'AUD',
    Awg: 'AWG',
    Azn: 'AZN',
    Bam: 'BAM',
    Bbd: 'BBD',
    Bdt: 'BDT',
    Bgn: 'BGN',
    Bhd: 'BHD',
    Bif: 'BIF',
    Bmd: 'BMD',
    Bnd: 'BND',
    Bob: 'BOB',
    Brl: 'BRL',
    Bsd: 'BSD',
    Btn: 'BTN',
    Bwp: 'BWP',
    Byr: 'BYR',
    Bzd: 'BZD',
    Cad: 'CAD',
    Cdf: 'CDF',
    Chf: 'CHF',
    Clp: 'CLP',
    Cny: 'CNY',
    Cop: 'COP',
    Crc: 'CRC',
    Cuc: 'CUC',
    Cup: 'CUP',
    Cve: 'CVE',
    Czk: 'CZK',
    Djf: 'DJF',
    Dkk: 'DKK',
    Dop: 'DOP',
    Dzd: 'DZD',
    Egp: 'EGP',
    Ern: 'ERN',
    Etb: 'ETB',
    Eur: 'EUR',
    Fjd: 'FJD',
    Fkp: 'FKP',
    Gbp: 'GBP',
    Gel: 'GEL',
    Ggp: 'GGP',
    Ghs: 'GHS',
    Gip: 'GIP',
    Gmd: 'GMD',
    Gnf: 'GNF',
    Gtq: 'GTQ',
    Gyd: 'GYD',
    Hkd: 'HKD',
    Hnl: 'HNL',
    Hrk: 'HRK',
    Htg: 'HTG',
    Huf: 'HUF',
    Idr: 'IDR',
    Ils: 'ILS',
    Imp: 'IMP',
    Inr: 'INR',
    Iqd: 'IQD',
    Irr: 'IRR',
    Isk: 'ISK',
    Jep: 'JEP',
    Jmd: 'JMD',
    Jod: 'JOD',
    Jpy: 'JPY',
    Kes: 'KES',
    Kgs: 'KGS',
    Khr: 'KHR',
    Kmf: 'KMF',
    Kpw: 'KPW',
    Krw: 'KRW',
    Kwd: 'KWD',
    Kyd: 'KYD',
    Kzt: 'KZT',
    Lak: 'LAK',
    Lbp: 'LBP',
    Lkr: 'LKR',
    Lrd: 'LRD',
    Lsl: 'LSL',
    Ltl: 'LTL',
    Lvl: 'LVL',
    Lyd: 'LYD',
    Mad: 'MAD',
    Mdl: 'MDL',
    Mga: 'MGA',
    Mkd: 'MKD',
    Mmk: 'MMK',
    Mnt: 'MNT',
    Mop: 'MOP',
    Mro: 'MRO',
    Mur: 'MUR',
    Mvr: 'MVR',
    Mwk: 'MWK',
    Mxn: 'MXN',
    Myr: 'MYR',
    Mzn: 'MZN',
    Nad: 'NAD',
    Ngn: 'NGN',
    Nio: 'NIO',
    Nok: 'NOK',
    Npr: 'NPR',
    Nzd: 'NZD',
    Omr: 'OMR',
    Pab: 'PAB',
    Pen: 'PEN',
    Pgk: 'PGK',
    Php: 'PHP',
    Pkr: 'PKR',
    Pln: 'PLN',
    Pyg: 'PYG',
    Qar: 'QAR',
    Ron: 'RON',
    Rsd: 'RSD',
    Rub: 'RUB',
    Rwf: 'RWF',
    Sar: 'SAR',
    Sbd: 'SBD',
    Scr: 'SCR',
    Sdg: 'SDG',
    Sek: 'SEK',
    Sgd: 'SGD',
    Shp: 'SHP',
    Sll: 'SLL',
    Sos: 'SOS',
    Spl: 'SPL',
    Srd: 'SRD',
    Std: 'STD',
    Svc: 'SVC',
    Syp: 'SYP',
    Szl: 'SZL',
    Thb: 'THB',
    Tjs: 'TJS',
    Tmt: 'TMT',
    Tnd: 'TND',
    Top: 'TOP',
    Try: 'TRY',
    Ttd: 'TTD',
    Tvd: 'TVD',
    Twd: 'TWD',
    Tzs: 'TZS',
    Uah: 'UAH',
    Ugx: 'UGX',
    Usd: 'USD',
    Uyu: 'UYU',
    Uzs: 'UZS',
    Vef: 'VEF',
    Vnd: 'VND',
    Vuv: 'VUV',
    Wst: 'WST',
    Xaf: 'XAF',
    Xcd: 'XCD',
    Xdr: 'XDR',
    Xof: 'XOF',
    Xpf: 'XPF',
    Yer: 'YER',
    Zar: 'ZAR',
    Zmw: 'ZMW',
    Zwd: 'ZWD',
    Btc: 'BTC'
} as const;
export type PaymentAttemptCurrencyEnum = typeof PaymentAttemptCurrencyEnum[keyof typeof PaymentAttemptCurrencyEnum];


/**
 * Check if a given object implements the PaymentAttempt interface.
 */
export function instanceOfPaymentAttempt(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaymentAttemptFromJSON(json: any): PaymentAttempt {
    return PaymentAttemptFromJSONTyped(json, false);
}

export function PaymentAttemptFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentAttempt {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': !exists(json, 'accountId') ? undefined : json['accountId'],
        'paymentMethodId': !exists(json, 'paymentMethodId') ? undefined : json['paymentMethodId'],
        'paymentExternalKey': !exists(json, 'paymentExternalKey') ? undefined : json['paymentExternalKey'],
        'transactionId': !exists(json, 'transactionId') ? undefined : json['transactionId'],
        'transactionExternalKey': !exists(json, 'transactionExternalKey') ? undefined : json['transactionExternalKey'],
        'transactionType': !exists(json, 'transactionType') ? undefined : json['transactionType'],
        'effectiveDate': !exists(json, 'effectiveDate') ? undefined : (new Date(json['effectiveDate'])),
        'stateName': !exists(json, 'stateName') ? undefined : json['stateName'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'pluginName': !exists(json, 'pluginName') ? undefined : json['pluginName'],
        'pluginProperties': !exists(json, 'pluginProperties') ? undefined : ((json['pluginProperties'] as Array<any>).map(PluginPropertyFromJSON)),
        'auditLogs': !exists(json, 'auditLogs') ? undefined : ((json['auditLogs'] as Array<any>).map(AuditLogFromJSON)),
    };
}

export function PaymentAttemptToJSON(value?: PaymentAttempt | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
        'paymentMethodId': value.paymentMethodId,
        'paymentExternalKey': value.paymentExternalKey,
        'transactionId': value.transactionId,
        'transactionExternalKey': value.transactionExternalKey,
        'transactionType': value.transactionType,
        'effectiveDate': value.effectiveDate === undefined ? undefined : (value.effectiveDate.toISOString()),
        'stateName': value.stateName,
        'amount': value.amount,
        'currency': value.currency,
        'pluginName': value.pluginName,
        'pluginProperties': value.pluginProperties === undefined ? undefined : ((value.pluginProperties as Array<any>).map(PluginPropertyToJSON)),
        'auditLogs': value.auditLogs === undefined ? undefined : ((value.auditLogs as Array<any>).map(AuditLogToJSON)),
    };
}

