/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
} from './Price';

/**
 * 
 * @export
 * @interface PlanDetail
 */
export interface PlanDetail {
    /**
     * 
     * @type {string}
     * @memberof PlanDetail
     */
    product?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanDetail
     */
    plan?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanDetail
     */
    priceList?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanDetail
     */
    finalPhaseBillingPeriod?: PlanDetailFinalPhaseBillingPeriodEnum;
    /**
     * 
     * @type {Array<Price>}
     * @memberof PlanDetail
     */
    finalPhaseRecurringPrice?: Array<Price>;
}


/**
 * @export
 */
export const PlanDetailFinalPhaseBillingPeriodEnum = {
    Daily: 'DAILY',
    Weekly: 'WEEKLY',
    Biweekly: 'BIWEEKLY',
    ThirtyDays: 'THIRTY_DAYS',
    ThirtyOneDays: 'THIRTY_ONE_DAYS',
    SixtyDays: 'SIXTY_DAYS',
    NinetyDays: 'NINETY_DAYS',
    Monthly: 'MONTHLY',
    Bimestrial: 'BIMESTRIAL',
    Quarterly: 'QUARTERLY',
    Triannual: 'TRIANNUAL',
    Biannual: 'BIANNUAL',
    Annual: 'ANNUAL',
    Sesquiennial: 'SESQUIENNIAL',
    Biennial: 'BIENNIAL',
    Triennial: 'TRIENNIAL',
    NoBillingPeriod: 'NO_BILLING_PERIOD'
} as const;
export type PlanDetailFinalPhaseBillingPeriodEnum = typeof PlanDetailFinalPhaseBillingPeriodEnum[keyof typeof PlanDetailFinalPhaseBillingPeriodEnum];


/**
 * Check if a given object implements the PlanDetail interface.
 */
export function instanceOfPlanDetail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlanDetailFromJSON(json: any): PlanDetail {
    return PlanDetailFromJSONTyped(json, false);
}

export function PlanDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'product': !exists(json, 'product') ? undefined : json['product'],
        'plan': !exists(json, 'plan') ? undefined : json['plan'],
        'priceList': !exists(json, 'priceList') ? undefined : json['priceList'],
        'finalPhaseBillingPeriod': !exists(json, 'finalPhaseBillingPeriod') ? undefined : json['finalPhaseBillingPeriod'],
        'finalPhaseRecurringPrice': !exists(json, 'finalPhaseRecurringPrice') ? undefined : ((json['finalPhaseRecurringPrice'] as Array<any>).map(PriceFromJSON)),
    };
}

export function PlanDetailToJSON(value?: PlanDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product': value.product,
        'plan': value.plan,
        'priceList': value.priceList,
        'finalPhaseBillingPeriod': value.finalPhaseBillingPeriod,
        'finalPhaseRecurringPrice': value.finalPhaseRecurringPrice === undefined ? undefined : ((value.finalPhaseRecurringPrice as Array<any>).map(PriceToJSON)),
    };
}

