/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Session
 */
export interface Session {
	/**
	 *
	 * @type {string}
	 * @memberof Session
	 */
	id?: string;
	/**
	 *
	 * @type {Date}
	 * @memberof Session
	 */
	startDate?: Date;
	/**
	 *
	 * @type {Date}
	 * @memberof Session
	 */
	lastAccessDate?: Date;
	/**
	 *
	 * @type {number}
	 * @memberof Session
	 */
	timeout?: number;
	/**
	 *
	 * @type {string}
	 * @memberof Session
	 */
	host?: string;
}

/**
 * Check if a given object implements the Session interface.
 */
export function instanceOfSession(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function SessionFromJSON(json: any): Session {
	return SessionFromJSONTyped(json, false);
}

export function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		id: !exists(json, 'id') ? undefined : json['id'],
		startDate: !exists(json, 'startDate') ? undefined : new Date(json['startDate']),
		lastAccessDate: !exists(json, 'lastAccessDate') ? undefined : new Date(json['lastAccessDate']),
		timeout: !exists(json, 'timeout') ? undefined : json['timeout'],
		host: !exists(json, 'host') ? undefined : json['host']
	};
}

export function SessionToJSON(value?: Session | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		id: value.id,
		startDate: value.startDate === undefined ? undefined : value.startDate.toISOString(),
		lastAccessDate:
			value.lastAccessDate === undefined ? undefined : value.lastAccessDate.toISOString(),
		timeout: value.timeout,
		host: value.host
	};
}
