/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Session } from './Session';
import { SessionFromJSON, SessionFromJSONTyped, SessionToJSON } from './Session';

/**
 *
 * @export
 * @interface Subject
 */
export interface Subject {
	/**
	 *
	 * @type {string}
	 * @memberof Subject
	 */
	principal?: string;
	/**
	 *
	 * @type {boolean}
	 * @memberof Subject
	 */
	isAuthenticated?: boolean;
	/**
	 *
	 * @type {boolean}
	 * @memberof Subject
	 */
	isRemembered?: boolean;
	/**
	 *
	 * @type {Session}
	 * @memberof Subject
	 */
	session?: Session;
}

/**
 * Check if a given object implements the Subject interface.
 */
export function instanceOfSubject(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function SubjectFromJSON(json: any): Subject {
	return SubjectFromJSONTyped(json, false);
}

export function SubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subject {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		principal: !exists(json, 'principal') ? undefined : json['principal'],
		isAuthenticated: !exists(json, 'isAuthenticated') ? undefined : json['isAuthenticated'],
		isRemembered: !exists(json, 'isRemembered') ? undefined : json['isRemembered'],
		session: !exists(json, 'session') ? undefined : SessionFromJSON(json['session'])
	};
}

export function SubjectToJSON(value?: Subject | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		principal: value.principal,
		isAuthenticated: value.isAuthenticated,
		isRemembered: value.isRemembered,
		session: SessionToJSON(value.session)
	};
}
