/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Unit
 */
export interface Unit {
	/**
	 *
	 * @type {string}
	 * @memberof Unit
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Unit
	 */
	prettyName?: string;
}

/**
 * Check if a given object implements the Unit interface.
 */
export function instanceOfUnit(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function UnitFromJSON(json: any): Unit {
	return UnitFromJSONTyped(json, false);
}

export function UnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Unit {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		name: !exists(json, 'name') ? undefined : json['name'],
		prettyName: !exists(json, 'prettyName') ? undefined : json['prettyName']
	};
}

export function UnitToJSON(value?: Unit | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		name: value.name,
		prettyName: value.prettyName
	};
}
