/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Subscription } from './Subscription';
import {
	SubscriptionFromJSON,
	SubscriptionFromJSONTyped,
	SubscriptionToJSON
} from './Subscription';

/**
 *
 * @export
 * @interface BulkSubscriptionsBundle
 */
export interface BulkSubscriptionsBundle {
	/**
	 *
	 * @type {Array<Subscription>}
	 * @memberof BulkSubscriptionsBundle
	 */
	baseEntitlementAndAddOns: Array<Subscription>;
}

/**
 * Check if a given object implements the BulkSubscriptionsBundle interface.
 */
export function instanceOfBulkSubscriptionsBundle(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'baseEntitlementAndAddOns' in value;

	return isInstance;
}

export function BulkSubscriptionsBundleFromJSON(json: any): BulkSubscriptionsBundle {
	return BulkSubscriptionsBundleFromJSONTyped(json, false);
}

export function BulkSubscriptionsBundleFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): BulkSubscriptionsBundle {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		baseEntitlementAndAddOns: (json['baseEntitlementAndAddOns'] as Array<any>).map(
			SubscriptionFromJSON
		)
	};
}

export function BulkSubscriptionsBundleToJSON(value?: BulkSubscriptionsBundle | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		baseEntitlementAndAddOns: (value.baseEntitlementAndAddOns as Array<any>).map(SubscriptionToJSON)
	};
}
