/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Limit
 */
export interface Limit {
	/**
	 *
	 * @type {string}
	 * @memberof Limit
	 */
	unit?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Limit
	 */
	max?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Limit
	 */
	min?: string;
}

/**
 * Check if a given object implements the Limit interface.
 */
export function instanceOfLimit(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function LimitFromJSON(json: any): Limit {
	return LimitFromJSONTyped(json, false);
}

export function LimitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Limit {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		unit: !exists(json, 'unit') ? undefined : json['unit'],
		max: !exists(json, 'max') ? undefined : json['max'],
		min: !exists(json, 'min') ? undefined : json['min']
	};
}

export function LimitToJSON(value?: Limit | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		unit: value.unit,
		max: value.max,
		min: value.min
	};
}
