/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PluginServiceInfo
 */
export interface PluginServiceInfo {
	/**
	 *
	 * @type {string}
	 * @memberof PluginServiceInfo
	 */
	serviceTypeName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof PluginServiceInfo
	 */
	registrationName?: string;
}

/**
 * Check if a given object implements the PluginServiceInfo interface.
 */
export function instanceOfPluginServiceInfo(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function PluginServiceInfoFromJSON(json: any): PluginServiceInfo {
	return PluginServiceInfoFromJSONTyped(json, false);
}

export function PluginServiceInfoFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): PluginServiceInfo {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		serviceTypeName: !exists(json, 'serviceTypeName') ? undefined : json['serviceTypeName'],
		registrationName: !exists(json, 'registrationName') ? undefined : json['registrationName']
	};
}

export function PluginServiceInfoToJSON(value?: PluginServiceInfo | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		serviceTypeName: value.serviceTypeName,
		registrationName: value.registrationName
	};
}
