/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PriceList
 */
export interface PriceList {
	/**
	 *
	 * @type {string}
	 * @memberof PriceList
	 */
	name?: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof PriceList
	 */
	plans?: Array<string>;
}

/**
 * Check if a given object implements the PriceList interface.
 */
export function instanceOfPriceList(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function PriceListFromJSON(json: any): PriceList {
	return PriceListFromJSONTyped(json, false);
}

export function PriceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceList {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		name: !exists(json, 'name') ? undefined : json['name'],
		plans: !exists(json, 'plans') ? undefined : json['plans']
	};
}

export function PriceListToJSON(value?: PriceList | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		name: value.name,
		plans: value.plans
	};
}
