/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RolledUpUnit } from './RolledUpUnit';
import {
	RolledUpUnitFromJSON,
	RolledUpUnitFromJSONTyped,
	RolledUpUnitToJSON
} from './RolledUpUnit';

/**
 *
 * @export
 * @interface RolledUpUsage
 */
export interface RolledUpUsage {
	/**
	 *
	 * @type {string}
	 * @memberof RolledUpUsage
	 */
	subscriptionId?: string;
	/**
	 *
	 * @type {Date}
	 * @memberof RolledUpUsage
	 */
	startDate?: Date;
	/**
	 *
	 * @type {Date}
	 * @memberof RolledUpUsage
	 */
	endDate?: Date;
	/**
	 *
	 * @type {Array<RolledUpUnit>}
	 * @memberof RolledUpUsage
	 */
	rolledUpUnits?: Array<RolledUpUnit>;
}

/**
 * Check if a given object implements the RolledUpUsage interface.
 */
export function instanceOfRolledUpUsage(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function RolledUpUsageFromJSON(json: any): RolledUpUsage {
	return RolledUpUsageFromJSONTyped(json, false);
}

export function RolledUpUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RolledUpUsage {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		subscriptionId: !exists(json, 'subscriptionId') ? undefined : json['subscriptionId'],
		startDate: !exists(json, 'startDate') ? undefined : new Date(json['startDate']),
		endDate: !exists(json, 'endDate') ? undefined : new Date(json['endDate']),
		rolledUpUnits: !exists(json, 'rolledUpUnits')
			? undefined
			: (json['rolledUpUnits'] as Array<any>).map(RolledUpUnitFromJSON)
	};
}

export function RolledUpUsageToJSON(value?: RolledUpUsage | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		subscriptionId: value.subscriptionId,
		startDate: value.startDate === undefined ? undefined : value.startDate.toISOString(),
		endDate: value.endDate === undefined ? undefined : value.endDate.toISOString(),
		rolledUpUnits:
			value.rolledUpUnits === undefined
				? undefined
				: (value.rolledUpUnits as Array<any>).map(RolledUpUnitToJSON)
	};
}
