/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RolledUpUnit
 */
export interface RolledUpUnit {
	/**
	 *
	 * @type {string}
	 * @memberof RolledUpUnit
	 */
	unitType?: string;
	/**
	 *
	 * @type {number}
	 * @memberof RolledUpUnit
	 */
	amount?: number;
}

/**
 * Check if a given object implements the RolledUpUnit interface.
 */
export function instanceOfRolledUpUnit(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function RolledUpUnitFromJSON(json: any): RolledUpUnit {
	return RolledUpUnitFromJSONTyped(json, false);
}

export function RolledUpUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): RolledUpUnit {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		unitType: !exists(json, 'unitType') ? undefined : json['unitType'],
		amount: !exists(json, 'amount') ? undefined : json['amount']
	};
}

export function RolledUpUnitToJSON(value?: RolledUpUnit | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		unitType: value.unitType,
		amount: value.amount
	};
}
