/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SimplePlan
 */
export interface SimplePlan {
	/**
	 *
	 * @type {string}
	 * @memberof SimplePlan
	 */
	planId?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SimplePlan
	 */
	productName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof SimplePlan
	 */
	productCategory?: SimplePlanProductCategoryEnum;
	/**
	 *
	 * @type {string}
	 * @memberof SimplePlan
	 */
	currency?: SimplePlanCurrencyEnum;
	/**
	 *
	 * @type {number}
	 * @memberof SimplePlan
	 */
	amount?: number;
	/**
	 *
	 * @type {string}
	 * @memberof SimplePlan
	 */
	billingPeriod?: SimplePlanBillingPeriodEnum;
	/**
	 *
	 * @type {number}
	 * @memberof SimplePlan
	 */
	trialLength?: number;
	/**
	 *
	 * @type {string}
	 * @memberof SimplePlan
	 */
	trialTimeUnit?: SimplePlanTrialTimeUnitEnum;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof SimplePlan
	 */
	availableBaseProducts?: Array<string>;
}

/**
 * @export
 */
export const SimplePlanProductCategoryEnum = {
	Base: 'BASE',
	AddOn: 'ADD_ON',
	Standalone: 'STANDALONE'
} as const;
export type SimplePlanProductCategoryEnum =
	(typeof SimplePlanProductCategoryEnum)[keyof typeof SimplePlanProductCategoryEnum];

/**
 * @export
 */
export const SimplePlanCurrencyEnum = {
	Aed: 'AED',
	Afn: 'AFN',
	All: 'ALL',
	Amd: 'AMD',
	Ang: 'ANG',
	Aoa: 'AOA',
	Ars: 'ARS',
	Aud: 'AUD',
	Awg: 'AWG',
	Azn: 'AZN',
	Bam: 'BAM',
	Bbd: 'BBD',
	Bdt: 'BDT',
	Bgn: 'BGN',
	Bhd: 'BHD',
	Bif: 'BIF',
	Bmd: 'BMD',
	Bnd: 'BND',
	Bob: 'BOB',
	Brl: 'BRL',
	Bsd: 'BSD',
	Btn: 'BTN',
	Bwp: 'BWP',
	Byr: 'BYR',
	Bzd: 'BZD',
	Cad: 'CAD',
	Cdf: 'CDF',
	Chf: 'CHF',
	Clp: 'CLP',
	Cny: 'CNY',
	Cop: 'COP',
	Crc: 'CRC',
	Cuc: 'CUC',
	Cup: 'CUP',
	Cve: 'CVE',
	Czk: 'CZK',
	Djf: 'DJF',
	Dkk: 'DKK',
	Dop: 'DOP',
	Dzd: 'DZD',
	Egp: 'EGP',
	Ern: 'ERN',
	Etb: 'ETB',
	Eur: 'EUR',
	Fjd: 'FJD',
	Fkp: 'FKP',
	Gbp: 'GBP',
	Gel: 'GEL',
	Ggp: 'GGP',
	Ghs: 'GHS',
	Gip: 'GIP',
	Gmd: 'GMD',
	Gnf: 'GNF',
	Gtq: 'GTQ',
	Gyd: 'GYD',
	Hkd: 'HKD',
	Hnl: 'HNL',
	Hrk: 'HRK',
	Htg: 'HTG',
	Huf: 'HUF',
	Idr: 'IDR',
	Ils: 'ILS',
	Imp: 'IMP',
	Inr: 'INR',
	Iqd: 'IQD',
	Irr: 'IRR',
	Isk: 'ISK',
	Jep: 'JEP',
	Jmd: 'JMD',
	Jod: 'JOD',
	Jpy: 'JPY',
	Kes: 'KES',
	Kgs: 'KGS',
	Khr: 'KHR',
	Kmf: 'KMF',
	Kpw: 'KPW',
	Krw: 'KRW',
	Kwd: 'KWD',
	Kyd: 'KYD',
	Kzt: 'KZT',
	Lak: 'LAK',
	Lbp: 'LBP',
	Lkr: 'LKR',
	Lrd: 'LRD',
	Lsl: 'LSL',
	Ltl: 'LTL',
	Lvl: 'LVL',
	Lyd: 'LYD',
	Mad: 'MAD',
	Mdl: 'MDL',
	Mga: 'MGA',
	Mkd: 'MKD',
	Mmk: 'MMK',
	Mnt: 'MNT',
	Mop: 'MOP',
	Mro: 'MRO',
	Mur: 'MUR',
	Mvr: 'MVR',
	Mwk: 'MWK',
	Mxn: 'MXN',
	Myr: 'MYR',
	Mzn: 'MZN',
	Nad: 'NAD',
	Ngn: 'NGN',
	Nio: 'NIO',
	Nok: 'NOK',
	Npr: 'NPR',
	Nzd: 'NZD',
	Omr: 'OMR',
	Pab: 'PAB',
	Pen: 'PEN',
	Pgk: 'PGK',
	Php: 'PHP',
	Pkr: 'PKR',
	Pln: 'PLN',
	Pyg: 'PYG',
	Qar: 'QAR',
	Ron: 'RON',
	Rsd: 'RSD',
	Rub: 'RUB',
	Rwf: 'RWF',
	Sar: 'SAR',
	Sbd: 'SBD',
	Scr: 'SCR',
	Sdg: 'SDG',
	Sek: 'SEK',
	Sgd: 'SGD',
	Shp: 'SHP',
	Sll: 'SLL',
	Sos: 'SOS',
	Spl: 'SPL',
	Srd: 'SRD',
	Std: 'STD',
	Svc: 'SVC',
	Syp: 'SYP',
	Szl: 'SZL',
	Thb: 'THB',
	Tjs: 'TJS',
	Tmt: 'TMT',
	Tnd: 'TND',
	Top: 'TOP',
	Try: 'TRY',
	Ttd: 'TTD',
	Tvd: 'TVD',
	Twd: 'TWD',
	Tzs: 'TZS',
	Uah: 'UAH',
	Ugx: 'UGX',
	Usd: 'USD',
	Uyu: 'UYU',
	Uzs: 'UZS',
	Vef: 'VEF',
	Vnd: 'VND',
	Vuv: 'VUV',
	Wst: 'WST',
	Xaf: 'XAF',
	Xcd: 'XCD',
	Xdr: 'XDR',
	Xof: 'XOF',
	Xpf: 'XPF',
	Yer: 'YER',
	Zar: 'ZAR',
	Zmw: 'ZMW',
	Zwd: 'ZWD',
	Btc: 'BTC'
} as const;
export type SimplePlanCurrencyEnum =
	(typeof SimplePlanCurrencyEnum)[keyof typeof SimplePlanCurrencyEnum];

/**
 * @export
 */
export const SimplePlanBillingPeriodEnum = {
	Daily: 'DAILY',
	Weekly: 'WEEKLY',
	Biweekly: 'BIWEEKLY',
	ThirtyDays: 'THIRTY_DAYS',
	ThirtyOneDays: 'THIRTY_ONE_DAYS',
	SixtyDays: 'SIXTY_DAYS',
	NinetyDays: 'NINETY_DAYS',
	Monthly: 'MONTHLY',
	Bimestrial: 'BIMESTRIAL',
	Quarterly: 'QUARTERLY',
	Triannual: 'TRIANNUAL',
	Biannual: 'BIANNUAL',
	Annual: 'ANNUAL',
	Sesquiennial: 'SESQUIENNIAL',
	Biennial: 'BIENNIAL',
	Triennial: 'TRIENNIAL',
	NoBillingPeriod: 'NO_BILLING_PERIOD'
} as const;
export type SimplePlanBillingPeriodEnum =
	(typeof SimplePlanBillingPeriodEnum)[keyof typeof SimplePlanBillingPeriodEnum];

/**
 * @export
 */
export const SimplePlanTrialTimeUnitEnum = {
	Days: 'DAYS',
	Weeks: 'WEEKS',
	Months: 'MONTHS',
	Years: 'YEARS',
	Unlimited: 'UNLIMITED'
} as const;
export type SimplePlanTrialTimeUnitEnum =
	(typeof SimplePlanTrialTimeUnitEnum)[keyof typeof SimplePlanTrialTimeUnitEnum];

/**
 * Check if a given object implements the SimplePlan interface.
 */
export function instanceOfSimplePlan(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function SimplePlanFromJSON(json: any): SimplePlan {
	return SimplePlanFromJSONTyped(json, false);
}

export function SimplePlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimplePlan {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		planId: !exists(json, 'planId') ? undefined : json['planId'],
		productName: !exists(json, 'productName') ? undefined : json['productName'],
		productCategory: !exists(json, 'productCategory') ? undefined : json['productCategory'],
		currency: !exists(json, 'currency') ? undefined : json['currency'],
		amount: !exists(json, 'amount') ? undefined : json['amount'],
		billingPeriod: !exists(json, 'billingPeriod') ? undefined : json['billingPeriod'],
		trialLength: !exists(json, 'trialLength') ? undefined : json['trialLength'],
		trialTimeUnit: !exists(json, 'trialTimeUnit') ? undefined : json['trialTimeUnit'],
		availableBaseProducts: !exists(json, 'availableBaseProducts')
			? undefined
			: json['availableBaseProducts']
	};
}

export function SimplePlanToJSON(value?: SimplePlan | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		planId: value.planId,
		productName: value.productName,
		productCategory: value.productCategory,
		currency: value.currency,
		amount: value.amount,
		billingPeriod: value.billingPeriod,
		trialLength: value.trialLength,
		trialTimeUnit: value.trialTimeUnit,
		availableBaseProducts: value.availableBaseProducts
	};
}
