/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlockPrice } from './BlockPrice';
import { BlockPriceFromJSON, BlockPriceFromJSONTyped, BlockPriceToJSON } from './BlockPrice';

/**
 *
 * @export
 * @interface TierPrice
 */
export interface TierPrice {
	/**
	 *
	 * @type {Array<BlockPrice>}
	 * @memberof TierPrice
	 */
	blockPrices?: Array<BlockPrice>;
}

/**
 * Check if a given object implements the TierPrice interface.
 */
export function instanceOfTierPrice(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function TierPriceFromJSON(json: any): TierPrice {
	return TierPriceFromJSONTyped(json, false);
}

export function TierPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TierPrice {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		blockPrices: !exists(json, 'blockPrices')
			? undefined
			: (json['blockPrices'] as Array<any>).map(BlockPriceFromJSON)
	};
}

export function TierPriceToJSON(value?: TierPrice | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		blockPrices:
			value.blockPrices === undefined
				? undefined
				: (value.blockPrices as Array<any>).map(BlockPriceToJSON)
	};
}
