/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsageRecord } from './UsageRecord';
import { UsageRecordFromJSON, UsageRecordFromJSONTyped, UsageRecordToJSON } from './UsageRecord';

/**
 *
 * @export
 * @interface UnitUsageRecord
 */
export interface UnitUsageRecord {
	/**
	 *
	 * @type {string}
	 * @memberof UnitUsageRecord
	 */
	unitType?: string;
	/**
	 *
	 * @type {Array<UsageRecord>}
	 * @memberof UnitUsageRecord
	 */
	usageRecords?: Array<UsageRecord>;
}

/**
 * Check if a given object implements the UnitUsageRecord interface.
 */
export function instanceOfUnitUsageRecord(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function UnitUsageRecordFromJSON(json: any): UnitUsageRecord {
	return UnitUsageRecordFromJSONTyped(json, false);
}

export function UnitUsageRecordFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): UnitUsageRecord {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		unitType: !exists(json, 'unitType') ? undefined : json['unitType'],
		usageRecords: !exists(json, 'usageRecords')
			? undefined
			: (json['usageRecords'] as Array<any>).map(UsageRecordFromJSON)
	};
}

export function UnitUsageRecordToJSON(value?: UnitUsageRecord | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		unitType: value.unitType,
		usageRecords:
			value.usageRecords === undefined
				? undefined
				: (value.usageRecords as Array<any>).map(UsageRecordToJSON)
	};
}
