/* tslint:disable */
/* eslint-disable */
/**
 * Kill Bill
 * Kill Bill is an open-source billing and payments platform
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserRoles
 */
export interface UserRoles {
	/**
	 *
	 * @type {string}
	 * @memberof UserRoles
	 */
	username: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserRoles
	 */
	password: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof UserRoles
	 */
	roles: Array<string>;
}

/**
 * Check if a given object implements the UserRoles interface.
 */
export function instanceOfUserRoles(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'username' in value;
	isInstance = isInstance && 'password' in value;
	isInstance = isInstance && 'roles' in value;

	return isInstance;
}

export function UserRolesFromJSON(json: any): UserRoles {
	return UserRolesFromJSONTyped(json, false);
}

export function UserRolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoles {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		username: json['username'],
		password: json['password'],
		roles: json['roles']
	};
}

export function UserRolesToJSON(value?: UserRoles | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		username: value.username,
		password: value.password,
		roles: value.roles
	};
}
